name: PR Checks
on: [pull_request]
jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: create lldbinit file
        run: make lldbinit
      - name: run tests
        run: make test
      - name: Danger action
        uses: MeilCli/danger-action@v5.6.0
        with:
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      
