name: PR Checks
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: make lldb command
        run: Make lldb_command
      - name: initialize lldb
        run: lldb --source lldb-command &
      - name: Run tests
        run: make test
      - name: Danger
        run: brew install danger/tap/danger-swift && danger-swift ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
